"""Development and held-out tasks. Oracles execute outside the editable project."""
EXTRA = {}
def add(name,goal,seed,fixed,oracle,files=None,heldout=False):
    EXTRA[name]={'goal':goal,'files':{'solution.py':seed,**(files or {})},'fixed':{'solution.py':fixed},'oracle':oracle,'partition':'held-out' if heldout else 'development'}
add('python-cli','Implement solution.py CLI with --name and optional --times positive integer (default 1). Print Hello, NAME! once per line. Missing --name or --times <= 0 exits nonzero. Keep it runnable with python3.',
 'print("hello")\n',
 'import argparse\np=argparse.ArgumentParser();p.add_argument("--name",required=True);p.add_argument("--times",type=int,default=1);a=p.parse_args()\nif a.times<1:p.error("times must be positive")\nfor _ in range(a.times):print(f"Hello, {a.name}!")\n',
 'import subprocess,sys\ndef run(*args):return subprocess.run([sys.executable,"solution.py",*args],capture_output=True,text=True)\nr=run("--name","Cedar Tree","--times","2");assert r.returncode==0 and r.stdout=="Hello, Cedar Tree!\\n"*2\nassert run().returncode!=0\nassert run("--name","X","--times","0").returncode!=0\n')
add('python-config','Implement load(path) in solution.py. Read JSON config; port defaults to 8080; validate port is an integer (not bool) from 1 to 65535 and host is a nonempty string default localhost. Return host and port only. Raise ValueError for invalid fields.',
 'def load(path):\n return {}\n',
 'import json\ndef load(path):\n with open(path) as f:c=json.load(f)\n host=c.get("host","localhost");port=c.get("port",8080)\n if not isinstance(host,str) or not host or type(port)!=int or not 1<=port<=65535:raise ValueError("invalid config")\n return {"host":host,"port":port}\n',
 'from solution import load\nimport json,tempfile,pathlib\nwith tempfile.TemporaryDirectory() as d:\n p=pathlib.Path(d)/"config.json"\n for v,expect in [({}, {"host":"localhost","port":8080}),({"host":"x","port":65535},{"host":"x","port":65535})]:\n  p.write_text(json.dumps(v));assert load(p)==expect\n for v in [{"port":True},{"port":0},{"port":"80"},{"host":""}]:\n  p.write_text(json.dumps(v))\n  try:load(p)\n  except ValueError:pass\n  else:raise AssertionError(v)\n')
add('python-csv','Implement totals(csv_text) using CSV headers name,amount. Sum Decimal amounts per name and return string totals with two decimal places. Handle quoted comma-containing names and blank input; do not use binary floats.',
 'def totals(csv_text):\n return {}\n',
 'import csv,io\nfrom decimal import Decimal\ndef totals(csv_text):\n out={}\n for r in csv.DictReader(io.StringIO(csv_text)):out[r["name"]]=out.get(r["name"],Decimal(0))+Decimal(r["amount"])\n return {k:format(v,".2f") for k,v in out.items()}\n',
 'from solution import totals\nassert totals(\'name,amount\\n"Cedar, Inc",0.10\\n"Cedar, Inc",0.20\\nOak,-2.50\\n\')=={"Cedar, Inc":"0.30","Oak":"-2.50"}\nassert totals("")=={}\nassert totals("name,amount\\nA,9999999999999999.99\\nA,0.01\\n")=={"A":"10000000000000000.00"}\n')
add('python-migration','Implement migrate(connection) for SQLite. In one transaction create items(id integer primary key, name text not null), add active integer not null default 1 to existing/new items, preserve existing rows and be idempotent.',
 'def migrate(connection):\n connection.execute("drop table if exists items")\n',
 'def migrate(connection):\n with connection:\n  connection.execute("create table if not exists items(id integer primary key,name text not null)")\n  if "active" not in [r[1] for r in connection.execute("pragma table_info(items)")]:connection.execute("alter table items add column active integer not null default 1")\n',
 'from solution import migrate\nimport sqlite3\nc=sqlite3.connect(":memory:");c.execute("create table items(id integer primary key,name text not null)");c.execute("insert into items values(7,\'Cedar\')");c.commit()\nmigrate(c);migrate(c);assert c.execute("select * from items").fetchall()==[(7,"Cedar",1)]\nd=sqlite3.connect(":memory:");migrate(d);d.execute("insert into items(name) values(\'New\')");assert d.execute("select active from items").fetchone()==(1,)\n')
add('python-transaction','Implement transfer(db, sender, receiver, amount) for accounts(id integer primary key,balance integer). Transfer a positive integer amount atomically. Reject missing accounts, same accounts, bool/noninteger amounts, or insufficient funds with ValueError; balances remain unchanged on rejection.',
 'def transfer(db,sender,receiver,amount):\n pass\n',
 'def transfer(db,sender,receiver,amount):\n if type(amount)!=int or amount<=0 or sender==receiver:raise ValueError("invalid transfer")\n with db:\n  a=db.execute("select balance from accounts where id=?",(sender,)).fetchone();b=db.execute("select balance from accounts where id=?",(receiver,)).fetchone()\n  if not a or not b or a[0]<amount:raise ValueError("unavailable funds")\n  db.execute("update accounts set balance=balance-? where id=?",(amount,sender));db.execute("update accounts set balance=balance+? where id=?",(amount,receiver))\n',
 'from solution import transfer\nimport sqlite3\nc=sqlite3.connect(":memory:");c.execute("create table accounts(id integer primary key,balance integer)");c.executemany("insert into accounts values(?,?)",[(1,10),(2,0)]);c.commit()\ntransfer(c,1,2,4);assert c.execute("select balance from accounts order by id").fetchall()==[(6,),(4,)]\nfor args in [(1,3,2),(1,2,9),(1,1,1),(1,2,True),(1,2,-1)]:\n try:transfer(c,*args)\n except ValueError:pass\n else:raise AssertionError(args)\n assert c.execute("select balance from accounts order by id").fetchall()==[(6,),(4,)]\n')
add('python-pagination','Implement paginate(items,page,size) with pages starting at 1 and positive integer size; invalid page/size raises ValueError. Return {items:list,total:int,pages:int}; empty list has zero pages; pages beyond end return empty items.',
 'def paginate(items,page,size):\n return {}\n',
 'def paginate(items,page,size):\n if type(page)!=int or type(size)!=int or page<1 or size<1:raise ValueError("page/size")\n return {"items":list(items[(page-1)*size:page*size]),"total":len(items),"pages":(len(items)+size-1)//size}\n',
 'from solution import paginate\nassert paginate([1,2,3,4,5],2,2)=={"items":[3,4],"total":5,"pages":3}\nassert paginate([],1,5)=={"items":[],"total":0,"pages":0}\nassert paginate([1],9,1)["items"]==[]\nfor p,s in [(0,1),(1,0),(True,2),(1,1.5)]:\n try:paginate([],p,s)\n except ValueError:pass\n else:raise AssertionError((p,s))\n')
add('python-paths','Implement resolve_file(root,relative) returning a resolved pathlib.Path strictly inside root. Reject absolute paths, .. traversal, root itself, and symlinks escaping root with ValueError. Existing valid nested files work.',
 'def resolve_file(root,relative):\n return relative\n',
 'from pathlib import Path\ndef resolve_file(root,relative):\n root=Path(root).resolve();p=Path(relative)\n if p.is_absolute() or ".." in p.parts:raise ValueError("path")\n result=(root/p).resolve()\n if result==root or not result.is_relative_to(root):raise ValueError("outside")\n return result\n',
 'from solution import resolve_file\nfrom pathlib import Path\nimport tempfile\nwith tempfile.TemporaryDirectory() as d:\n base=Path(d);root=base/"root";root.mkdir();(root/"sub").mkdir();(root/"sub/a").write_text("x");(root/"link").symlink_to(base)\n assert resolve_file(root,"sub/a")==root/"sub/a"\n for path in ["../x",str(base),".","link/x"]:\n  try:resolve_file(root,path)\n  except ValueError:pass\n  else:raise AssertionError(path)\n')
add('python-cache','Implement Cache(ttl,clock) with set(key,value) and get(key,default=None). Values expire when elapsed >= ttl; ttl must be nonnegative. Use supplied clock, support None values and refresh expiry on overwrite.',
 'class Cache:\n pass\n',
 'class Cache:\n def __init__(self,ttl,clock):\n  if ttl<0:raise ValueError("ttl")\n  self.ttl=ttl;self.clock=clock;self.data={}\n def set(self,key,value):self.data[key]=(value,self.clock()+self.ttl)\n def get(self,key,default=None):\n  if key not in self.data:return default\n  value,expiry=self.data[key]\n  if self.clock()>=expiry:\n   del self.data[key];return default\n  return value\n',
 'from solution import Cache\nnow=[0];c=Cache(5,lambda:now[0]);c.set("a",None);assert c.get("a",7) is None\nnow[0]=4;c.set("a",2);now[0]=5;assert c.get("a")==2\nnow[0]=9;assert c.get("a","expired")=="expired"\nz=Cache(0,lambda:0);z.set("x",1);assert z.get("x") is None\n')
add('python-retry','Implement retry(fn,attempts) that invokes fn until success, retries only OSError up to attempts, returns successful value, and rethrows the last error on exhaustion. Positive integer attempts required; other exceptions are not retried.',
 'def retry(fn,attempts):\n return fn()\n',
 'def retry(fn,attempts):\n if type(attempts)!=int or attempts<1:raise ValueError("attempts")\n for i in range(attempts):\n  try:return fn()\n  except OSError:\n   if i==attempts-1:raise\n',
 'from solution import retry\ncalls=[]\ndef flaky():\n calls.append(1)\n if len(calls)<3:raise OSError("temporary")\n return 42\nassert retry(flaky,3)==42 and len(calls)==3\ndef bad():raise RuntimeError("permanent")\ntry:retry(bad,9)\nexcept RuntimeError:pass\nelse:raise AssertionError()\ntry:retry(lambda:None,0)\nexcept ValueError:pass\nelse:raise AssertionError()\n')
add('python-async','Implement async gather_values(functions,limit) where functions are async zero-argument callables. Run at most limit concurrently and return values in input order. limit must be positive; propagate exceptions.',
 'async def gather_values(functions,limit):\n return []\n',
 'import asyncio\nasync def gather_values(functions,limit):\n if limit<1:raise ValueError("limit")\n sem=asyncio.Semaphore(limit)\n async def run(fn):\n  async with sem:return await fn()\n return await asyncio.gather(*(run(fn) for fn in functions))\n',
 'import asyncio\nfrom solution import gather_values\nasync def main():\n active=[0,0]\n def make(n):\n  async def work():\n   active[0]+=1;active[1]=max(active);await asyncio.sleep(.005*(4-n));active[0]-=1;return n\n  return work\n assert await gather_values([make(i) for i in range(4)],2)==[0,1,2,3]\n assert active[1]==2\n assert await gather_values([],1)==[]\nasyncio.run(main())\n')
add('python-jsonl','Implement records(text) returning parsed JSON objects from nonblank lines. A malformed line or non-object JSON must raise ValueError identifying its 1-based line number. Preserve order.',
 'def records(text):\n return []\n',
 'import json\ndef records(text):\n out=[]\n for n,line in enumerate(text.splitlines(),1):\n  if not line.strip():continue\n  try:\n   value=json.loads(line)\n   if not isinstance(value,dict):raise ValueError()\n  except ValueError as e:raise ValueError(f"line {n}") from e\n  out.append(value)\n return out\n',
 'from solution import records\nassert records(\' {"a":1}\\n\\n{"b":2}\\n\')==[{"a":1},{"b":2}]\nfor value in ["bad","[]"]:\n try:records("\\n"+value)\n except ValueError as e:assert "2" in str(e)\n else:raise AssertionError()\n')
add('python-setup','Repair solution.py main() to load defaults.json relative to its own module file, not current working directory. Return its greeting and preserve the file. It must also work when imported from another working directory.',
 'import json\ndef main():\n return json.load(open("defaults.json"))["greeting"]\n',
 'import json\nfrom pathlib import Path\ndef main():\n with Path(__file__).with_name("defaults.json").open() as f:return json.load(f)["greeting"]\n',
 'import solution,os,tempfile\noriginal=os.getcwd()\nwith tempfile.TemporaryDirectory() as d:\n try:os.chdir(d);assert solution.main()=="Hello, Cedar"\n finally:os.chdir(original)\n',{'defaults.json':'{"greeting":"Hello, Cedar"}\n'})
add('python-dependency-api','Repair solution.py adapter compute(values) to use bundled vendor.math.total(values, strict=True), return its result, and preserve exceptions. The former add() function no longer exists; do not duplicate vendor logic.',
 'from vendor.math import add\ndef compute(values):return add(values)\n',
 'from vendor import math\ndef compute(values):return math.total(values,strict=True)\n',
 'import solution\nfrom vendor import math\nassert solution.compute([2,3])==5\nmath.total=lambda values,strict: (values,strict)\nimport importlib;importlib.reload(solution)\nassert solution.compute([7])==([7],True)\n',{'vendor/__init__.py':'','vendor/math.py':'def total(values,strict=False):\n if strict and any(type(v)!=int for v in values):raise ValueError("integers required")\n return sum(values)\n'})
add('python-service-config','Implement endpoint(environ) for a local service. Read PORT (default 8080) as an integer 1..65535 and HOST (default 127.0.0.1). Return http://host:port/health, enclosing IPv6 hosts in brackets. Invalid port raises ValueError.',
 'def endpoint(environ):\n return "http://localhost"\n',
 'def endpoint(environ):\n port=int(environ.get("PORT","8080"));host=environ.get("HOST","127.0.0.1")\n if not 1<=port<=65535:raise ValueError("port")\n if ":" in host and not host.startswith("["):host="["+host+"]"\n return f"http://{host}:{port}/health"\n',
 'from solution import endpoint\nassert endpoint({})=="http://127.0.0.1:8080/health"\nassert endpoint({"HOST":"::1","PORT":"3000"})=="http://[::1]:3000/health"\nfor p in ["0","65536","x"]:\n try:endpoint({"PORT":p})\n except ValueError:pass\n else:raise AssertionError(p)\n')
add('heldout-deduplicate','Implement unique(values,key) preserving the first value for each hashable key(value); retain input order and support unhashable values.',
 'def unique(values,key):return values\n',
 'def unique(values,key):\n seen=set();out=[]\n for value in values:\n  k=key(value)\n  if k not in seen:seen.add(k);out.append(value)\n return out\n',
 'from solution import unique\na=[{"id":2,"v":"a"},{"id":1},{"id":2,"v":"b"}]\nassert unique(a,lambda x:x["id"])==a[:2]\nassert unique([],str)==[]\n',heldout=True)
add('heldout-atomic-save','Implement save(path,text) atomically replacing a UTF-8 text file using a temporary file in the same directory; on os.replace failure preserve the old file and remove the temp. Use fsync before replace.',
 'def save(path,text):\n open(path,"w").write(text)\n',
 'import os,tempfile\nfrom pathlib import Path\ndef save(path,text):\n p=Path(path);name=None\n try:\n  with tempfile.NamedTemporaryFile(mode="w",encoding="utf8",dir=p.parent,delete=False) as f:\n   name=f.name;f.write(text);f.flush();os.fsync(f.fileno())\n  os.replace(name,p)\n finally:\n  if name and os.path.exists(name):os.unlink(name)\n',
 'from solution import save\nfrom pathlib import Path\nfrom unittest.mock import patch\nimport tempfile\nwith tempfile.TemporaryDirectory() as d:\n p=Path(d)/"x";p.write_text("old")\n with patch("os.replace",side_effect=OSError("fault")):\n  try:save(p,"new")\n  except OSError:pass\n  else:raise AssertionError("did not replace")\n assert p.read_text()=="old" and len(list(Path(d).iterdir()))==1\n save(p,"cedar ☃");assert p.read_text()=="cedar ☃"\n',heldout=True)
add('heldout-toposort','Implement order(dependencies) where dict maps each node to dependency names. Return a list with each dependency before its node, including dependency-only nodes. Raise ValueError on cycles. Preserve no particular sibling ordering.',
 'def order(dependencies):return list(dependencies)\n',
 'def order(dependencies):\n seen=set();active=set();out=[]\n def visit(n):\n  if n in active:raise ValueError("cycle")\n  if n in seen:return\n  active.add(n)\n  for d in dependencies.get(n,[]):visit(d)\n  active.remove(n);seen.add(n);out.append(n)\n for n in dependencies:visit(n)\n return out\n',
 'from solution import order\nr=order({"app":["db","web"],"web":["db"]});assert set(r)=={"app","db","web"} and r.index("db")<r.index("web")<r.index("app")\ntry:order({"a":["b"],"b":["a"]})\nexcept ValueError:pass\nelse:raise AssertionError("cycle")\n',heldout=True)
add('heldout-date','Implement utc_timestamp(text) for ISO 8601 datetime strings with required explicit timezone, accepting Z; return integer Unix seconds in UTC. Reject naive datetimes with ValueError.',
 'def utc_timestamp(text):return 0\n',
 'from datetime import datetime\ndef utc_timestamp(text):\n d=datetime.fromisoformat(text.replace("Z","+00:00"))\n if d.tzinfo is None:raise ValueError("timezone required")\n return int(d.timestamp())\n',
 'from solution import utc_timestamp\nassert utc_timestamp("2024-01-01T01:00:00+01:00")==1704067200\nassert utc_timestamp("2024-01-01T00:00:00Z")==1704067200\ntry:utc_timestamp("2024-01-01T00:00:00")\nexcept ValueError:pass\nelse:raise AssertionError()\n',heldout=True)
